// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Database;

public partial class AppRole
{
    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public virtual ICollection<UserRole> UserRole { get; set; } = new List<UserRole>();
}