// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Database;

public partial class Places
{
    public int PlaceId { get; set; }

    public string Title { get; set; }

    public string ImgSrc { get; set; }

    public string ImgAlt { get; set; }

    public string AddBy { get; set; }

    public string IsApproved { get; set; }

    public string IsDeleted { get; set; }

    public virtual ICollection<UserFavoritePlaces> UserFavoritePlaces { get; set; } = new List<UserFavoritePlaces>();
}