// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Database;

public partial class UserFavoritePlaces
{
    public int UserId { get; set; }

    public int PlaceId { get; set; }

    public virtual Places Place { get; set; }

    public virtual Users User { get; set; }
}