// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Database;

public partial class UserRole
{
    public int UserId { get; set; }

    public string RoleId { get; set; }

    public virtual AppRole Role { get; set; }

    public virtual Users User { get; set; }
}