// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Database;

public partial class Users
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public virtual ICollection<UserFavoritePlaces> UserFavoritePlaces { get; set; } = new List<UserFavoritePlaces>();

    public virtual ICollection<UserRole> UserRole { get; set; } = new List<UserRole>();
}