// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Domain.Database;
using Microsoft.EntityFrameworkCore;

namespace Domain.Database.Context;

public partial class FavoritePlacesContext : DbContext
{
    public FavoritePlacesContext(DbContextOptions<FavoritePlacesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AppRole> AppRole { get; set; }

    public virtual DbSet<Places> Places { get; set; }

    public virtual DbSet<PlacesComment> PlacesComment { get; set; }

    public virtual DbSet<UserFavoritePlaces> UserFavoritePlaces { get; set; }

    public virtual DbSet<UserRole> UserRole { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppRole>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__AppRole__760965CC37238FB2");

            entity.Property(e => e.RoleId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("role_id");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("role_name");
        });

        modelBuilder.Entity<Places>(entity =>
        {
            entity.HasKey(e => e.PlaceId).HasName("PK__Places__BF2B684AA3AFFB4F");

            entity.Property(e => e.PlaceId).HasColumnName("place_id");
            entity.Property(e => e.AddBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("user")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Places_add_by")
                .HasColumnName("add_by");
            entity.Property(e => e.ImgAlt)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("img_alt");
            entity.Property(e => e.ImgSrc)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("img_src");
            entity.Property(e => e.IsApproved)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue("N")
                .IsFixedLength()
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Places_isApproved")
                .HasColumnName("isApproved");
            entity.Property(e => e.IsDeleted)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue("N")
                .IsFixedLength()
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Places_isDeleted")
                .HasColumnName("isDeleted");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("title");
            entity.Property(e => e.UploadedUserId).HasColumnName("uploaded_user_id");
        });

        modelBuilder.Entity<PlacesComment>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.PlaceId });

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.PlaceId).HasColumnName("place_id");
            entity.Property(e => e.Comment)
                .HasColumnType("text")
                .HasColumnName("comment");
            entity.Property(e => e.Rating).HasColumnName("rating");

            entity.HasOne(d => d.Place).WithMany(p => p.PlacesComment)
                .HasForeignKey(d => d.PlaceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlacesComment_Places");

            entity.HasOne(d => d.User).WithMany(p => p.PlacesComment)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlacesComment_Users");
        });

        modelBuilder.Entity<UserFavoritePlaces>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.PlaceId });

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.PlaceId).HasColumnName("place_id");

            entity.HasOne(d => d.Place).WithMany(p => p.UserFavoritePlaces)
                .HasForeignKey(d => d.PlaceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserFavor__place__403A8C7D");

            entity.HasOne(d => d.User).WithMany(p => p.UserFavoritePlaces)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserFavor__user___412EB0B6");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId });

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.RoleId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("role_id");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRole)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserRole__role_i__4222D4EF");

            entity.HasOne(d => d.User).WithMany(p => p.UserRole)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserRole__user_i__4316F928");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__B9BE370F25216D30");

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("password");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("user_name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}