USE [master]
GO

/****** Object:  Database [FavoritePlaces]    Script Date: 17/7/2569 7:31:08 ******/
CREATE DATABASE [FavoritePlaces]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FavoritePlaces', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\FavoritePlaces.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FavoritePlaces_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\FavoritePlaces_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FavoritePlaces].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FavoritePlaces] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FavoritePlaces] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FavoritePlaces] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FavoritePlaces] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FavoritePlaces] SET ARITHABORT OFF 
GO

ALTER DATABASE [FavoritePlaces] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FavoritePlaces] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FavoritePlaces] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FavoritePlaces] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FavoritePlaces] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FavoritePlaces] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FavoritePlaces] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FavoritePlaces] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FavoritePlaces] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FavoritePlaces] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FavoritePlaces] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FavoritePlaces] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FavoritePlaces] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FavoritePlaces] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FavoritePlaces] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FavoritePlaces] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FavoritePlaces] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FavoritePlaces] SET RECOVERY FULL 
GO

ALTER DATABASE [FavoritePlaces] SET  MULTI_USER 
GO

ALTER DATABASE [FavoritePlaces] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FavoritePlaces] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FavoritePlaces] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FavoritePlaces] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FavoritePlaces] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FavoritePlaces] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [FavoritePlaces] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FavoritePlaces] SET QUERY_STORE = ON
GO

ALTER DATABASE [FavoritePlaces] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [FavoritePlaces] SET  READ_WRITE 
GO

